version: '3.0'
services:
  mssql:
    image: microsoft/mssql-server-linux:latest
    ports:
      - 1433:1433
    volumes:
      - /var/opt/mssql
      - ./db/sql:/usr/src/app
    working_dir: /usr/src/app
    command: sh -c ' chmod +x ./start.sh; ./start.sh & /opt/mssql/bin/sqlservr;'
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: P@55w0rd
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '3050:4200'
    volumes:
      - /client/node_modules
      - ./client:/client
  api:
    depends_on:
      - mssql
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - '46304:80'
      - '44368:443'
    volumes:
      - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
      - ${HOME}/.aspnet/https:/root/.aspnet/https/
